version: '3.3'

services:
  smarkio_app:
    image: thiagosiqueira/dockersmarkio:latest
    ports:
      - '3000:3000'
    #volumes:
     # - .:/usr/app
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
    entrypoint: ./entrypoint.sh


  mysql:
    image: mysql
    ports:
      - '3306:3306'
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
      - ./volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=smarkio_watson
